Public Class P2
    Implements BaseProblem

    Public Function description() As String Implements BaseProblem.description
        Return "Each new term in the Fibonacci sequence is generated by adding the previous two terms. " +
            "By starting with 1 and 2, the first 10 terms will be:" + vbNewLine +
            "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..." +
            "By considering the terms in the Fibonacci sequence whose values do not exceed four million, " +
            "find the sum of the even-valued terms."
    End Function

    Public Function hints() As String Implements BaseProblem.hints
        Return ""
    End Function

    Public Function solve() As String Implements BaseProblem.solve
        Return ""
    End Function
End Class
