Public Class P12
    Implements BaseProblem

    Public Function description() As String Implements BaseProblem.description
        Return "The sequence of triangle numbers is generated by adding the natural numbers." +
            "So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:" + vbNewLine +
            "1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ..." + vbNewLine +
            "Let us list the factors of the first seven triangle numbers:" + vbNewLine +
            " 1: 1" + vbNewLine +
            " 3: 1,3" + vbNewLine +
            " 6: 1,2,3,6" + vbNewLine +
            "10: 1,2,5,10" + vbNewLine +
            "15: 1,3,5,15" + vbNewLine +
            "21: 1,3,7,21" + vbNewLine +
            "28: 1,2,4,7,14,28" + vbNewLine +
            "We can see that 28 is the first triangle number to have over five divisors." + vbNewLine +
            "What is the value of the first triangle number to have over five hundred divisors?"
    End Function

    Public Function hints() As String Implements BaseProblem.hints
        Return ""
    End Function

    Public Function solve() As String Implements BaseProblem.solve
        Return ""
    End Function
End Class
